"""
Extract Chainalysis Global Crypto Adoption Index ranking tables from PDFs.
Phase 2B.4.a Checkpoint 1 — one-time extraction script.
Uses PyMuPDF find_tables() for structured table extraction.

================================================================================
WARNING — READ BEFORE RE-RUNNING
================================================================================

This script is preserved for audit-trail purposes only. The CSVs in
data/01_raw/chainalysis/ are the canonical source from Checkpoint 2 onward
and should NOT be regenerated by re-running this script without addressing
the known issues below.

KNOWN ISSUE 1 — 2020 PDF requires separate vision/OCR extraction
    PyMuPDF find_tables() cannot extract the 2020 report's ranking tables.
    The 2020 CSV was produced by a manual vision-based extraction. Re-running
    this script will NOT regenerate adoption_index_2020.csv correctly.

KNOWN ISSUE 2 — "Among lowest" countries on page 130 of the 2020 PDF
    Even the manual vision extraction initially missed 10 countries listed
    in the "Among lowest" section on page 130 of the 2020 report (Cape Verde,
    Chad, Fiji, Laos, Libya, Mongolia, Tajikistan, Turkmenistan, West Bank
    and Gaza, Zimbabwe). These were added at Checkpoint 2 with rank=NaN,
    overall_score=0, and rank_note="Among lowest".

    Any future re-extraction must explicitly handle the "Among lowest"
    section, otherwise these 10 countries will be silently dropped again.
    See docs/CHECKPOINT_1_REPORT.md and docs/CHECKPOINT_2_REPORT.md for the
    full audit trail.

KNOWN ISSUE 3 — 2025 coverage ceiling
    The 2025 CSV stops at rank 130. This is Chainalysis's actual published
    coverage, not a parser truncation. Do not attempt to "fix" the 130-row
    count by extending the extraction range.

If you need to regenerate the CSVs from scratch, the procedure is:
    1. Re-download the source PDFs (URLs in data/01_raw/chainalysis/SOURCES.md)
    2. Run this script for years 2021–2025
    3. Manually re-extract 2020 using vision/OCR, INCLUDING the page-130
       "Among lowest" section
    4. Run scripts/standardize_country_names.py to add country_iso3 codes

DO NOT run this script blindly. Read CHECKPOINT_1_REPORT.md first.
================================================================================
"""
import fitz
import os
import sys
import csv
import re

sys.stdout.reconfigure(encoding='utf-8')

BASE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    'data', '01_raw', 'chainalysis'
)


def clean_cell(val):
    """Clean a cell value."""
    if val is None:
        return ''
    val = str(val).replace('\n', ' ').replace('\u200b', '').strip()
    val = re.sub(r'\s+', ' ', val)
    return val


def extract_all_table_rows(pdf_path, page_range):
    """Extract all table rows from pages. Returns list of lists (cleaned)."""
    doc = fitz.open(pdf_path)
    all_rows = []
    for i in page_range:
        page = doc[i - 1]
        tabs = page.find_tables()
        for t in tabs.tables:
            for row_idx in range(t.row_count):
                row = [clean_cell(t.extract()[row_idx][c]) for c in range(t.col_count)]
                all_rows.append(row)
    doc.close()
    return all_rows


def is_header_row(row):
    """Check if a row looks like a table header."""
    text = ' '.join(str(v).lower() for v in row)
    return 'country' in text or 'ranking' in text or 'index' in text


def is_data_row(row, country_col, rank_col):
    """Check if a row has valid data (non-empty country and numeric rank)."""
    if not row[country_col]:
        return False
    try:
        int(row[rank_col])
        return True
    except (ValueError, IndexError):
        return False


def process_year(year, page_range, country_col, rank_col, sub_cols, sub_names,
                 score_col=None, skip_first_n=0):
    """
    Extract ranking data for a given year.

    Args:
        year: Report year
        page_range: range of 1-indexed page numbers
        country_col: column index for country name
        rank_col: column index for overall rank
        sub_cols: list of column indices for sub-index rankings
        sub_names: list of output column names for sub-indices
        score_col: column index for score (None if no score)
        skip_first_n: skip first N rows (for misdetected header artifacts)
    """
    pdf_path = os.path.join(BASE, f'adoption_index_{year}.pdf')
    all_rows = extract_all_table_rows(pdf_path, page_range)

    print(f"  {year}: {len(all_rows)} raw rows from pages {page_range.start}-{page_range.stop-1}")
    if all_rows:
        print(f"  Sample row 0: {all_rows[0][:5]}")
        if len(all_rows) > 1:
            print(f"  Sample row 1: {all_rows[1][:5]}")

    # Filter: skip headers and non-data rows
    data_rows = []
    for row in all_rows:
        if is_header_row(row):
            continue
        if is_data_row(row, country_col, rank_col):
            data_rows.append(row)

    # Build output
    output_header = ['country', 'rank']
    if score_col is not None:
        output_header.append('overall_score')
    output_header.extend(sub_names)

    outpath = os.path.join(BASE, f'adoption_index_{year}.csv')
    written = 0
    with open(outpath, 'w', newline='', encoding='utf-8') as f:
        w = csv.writer(f)
        w.writerow(output_header)
        for row in data_rows:
            try:
                country = row[country_col]
                rank = int(row[rank_col])
                out = [country, rank]
                if score_col is not None:
                    score = float(row[score_col]) if row[score_col] else ''
                    out.append(score)
                for sc in sub_cols:
                    val = int(row[sc]) if sc < len(row) and row[sc] else ''
                    out.append(val)
                w.writerow(out)
                written += 1
            except (ValueError, IndexError) as e:
                print(f"  WARNING: skipping row: {row[:4]}... ({e})")

    print(f"  {year}: wrote {written} rows to CSV")
    if data_rows:
        print(f"  Top 3: {[r[country_col] for r in data_rows[:3]]}")
        print(f"  Last 3: {[r[country_col] for r in data_rows[-3:]]}")
        # Sanity check: last rank should equal row count
        last_rank = int(data_rows[-1][rank_col])
        if last_rank != written:
            print(f"  NOTE: last rank={last_rank} != row_count={written}")
    return written


if __name__ == '__main__':
    print("=" * 60)
    print("Extracting Chainalysis Adoption Index tables (find_tables)")
    print("=" * 60)

    # 2021: 6 cols [Country, Score, Rank, Sub1, Sub2, Sub3]
    # Headers show: ['', '', '', 'On-chain value received', 'On-chain retail value received', 'P2P exchange trade volume']
    print("\n--- 2021 ---")
    process_year(2021, range(117, 124),
        country_col=0, rank_col=2, score_col=1,
        sub_cols=[3, 4, 5],
        sub_names=['onchain_value_received_rank',
                   'onchain_retail_value_received_rank',
                   'p2p_exchange_trade_volume_rank'])

    # 2022: 7 cols [Country, Rank, Sub1, Sub2, Sub3, Sub4, Sub5]
    print("\n--- 2022 ---")
    process_year(2022, range(82, 89),
        country_col=0, rank_col=1,
        sub_cols=[2, 3, 4, 5, 6],
        sub_names=['centralized_service_value_received_rank',
                   'retail_centralized_service_value_received_rank',
                   'p2p_exchange_trade_volume_rank',
                   'defi_value_received_rank',
                   'retail_defi_value_received_rank'])

    # 2023: 8 cols [Country, Region, Rank, Sub1, Sub2, Sub3, Sub4, Sub5]
    # No header row detected by find_tables; first row is India
    print("\n--- 2023 ---")
    process_year(2023, range(87, 97),
        country_col=0, rank_col=2,
        sub_cols=[3, 4, 5, 6, 7],
        sub_names=['centralized_service_value_received_rank',
                   'retail_centralized_service_value_received_rank',
                   'p2p_exchange_trade_volume_rank',
                   'defi_value_received_rank',
                   'retail_defi_value_received_rank'])

    # 2024: 7 cols [Country, Region, Rank, Sub1, Sub2, Sub3, Sub4]
    print("\n--- 2024 ---")
    process_year(2024, range(128, 134),
        country_col=0, rank_col=2,
        sub_cols=[3, 4, 5, 6],
        sub_names=['centralized_service_value_received_rank',
                   'retail_centralized_service_value_received_rank',
                   'defi_value_received_rank',
                   'retail_defi_value_received_rank'])

    # 2025: 7 cols [Country, Region, Rank, Sub1, Sub2, Sub3, Sub4]
    print("\n--- 2025 ---")
    process_year(2025, range(66, 73),
        country_col=0, rank_col=2,
        sub_cols=[3, 4, 5, 6],
        sub_names=['retail_centralized_service_value_received_rank',
                   'centralized_service_value_received_rank',
                   'defi_value_received_rank',
                   'institutional_centralized_service_value_received_rank'])

    print("\n" + "=" * 60)
    print("DONE. 2020 requires separate vision/OCR extraction.")
    print("=" * 60)
